/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package esame;

import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author Marco
 */
public class myFrame extends javax.swing.JFrame {
    
    Database db =null;
    Date dt= null;
    String lab;
    

    /**
     * Creates new form myFrame
     */
    public myFrame() {
        initComponents();
        Bnext.setVisible(false);
        Bprev.setVisible(false);
        db= new Database();
        
        credenziali cred = new credenziali(this, true, db);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        Bnext = new javax.swing.JButton();
        Bprev = new javax.swing.JButton();
        infolabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Gestione Aule");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Table.setCellSelectionEnabled(true);
        Table.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                reset(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        Bnext.setText("successivo");
        Bnext.setEnabled(false);
        Bnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnextActionPerformed(evt);
            }
        });

        Bprev.setText("precedente");
        Bprev.setEnabled(false);
        Bprev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BprevActionPerformed(evt);
            }
        });

        jMenu4.setText("Visualizza");

        jMenuItem4.setText("Utenti");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenu5.setText("Locali");

        jMenuItem3.setText("Occupazione lab");
        jMenuItem3.setToolTipText("Visualizza il piano di occupazione dei posti di un laboratorio");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem3);

        jMenuItem6.setText("Utenti autorizzati");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenuItem7.setText("Statistiche lab");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        jMenu4.add(jMenu5);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Aggiungi");

        jMenuItem2.setText("Utente");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem1.setText("Prenotazione");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem5.setText("Corso di laurea");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem8.setText("Gruppo");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(Bprev)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(infolabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Bnext)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bnext)
                    .addComponent(Bprev)
                    .addComponent(infolabel))
                .addGap(0, 53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        TableModelUtente tm = new TableModelUtente(db, this);
        Table.setModel(tm);
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        AddCorsoDialog co = new AddCorsoDialog(this, true, db);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        AggiungiDialog dia = new AggiungiDialog(this, true, db);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        DataChooser mychooser = new DataChooser(this, true,db);
        try{
            dt=mychooser.getData();
            lab=mychooser.getLab();
        TableModelOccupazione mytab = new TableModelOccupazione(lab,dt,db,this);
        Table.setModel(mytab);
        Bnext.setVisible(true);
        Bprev.setVisible(true);
        Bnext.setEnabled(true);
        Bprev.setEnabled(true);
        infolabel.setText("Laboratorio: "+lab+", giorno "+dt);
        }
        catch(Exception e)
        {
       
        }
        
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void reset(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_reset
        // TODO add your handling code here:
   
        Bnext.setVisible(false);
        Bprev.setVisible(false);
        Bnext.setEnabled(false);
        Bprev.setEnabled(false);
        infolabel.setText("");
    }//GEN-LAST:event_reset

    private void BnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnextActionPerformed
        // TODO add your handling code here:
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(dt);
        calendar.add(Calendar.DATE, 1);
        dt = calendar.getTime();
        TableModelOccupazione mytab = new TableModelOccupazione(lab,dt,db,this);
        Table.setModel(mytab);
        Bnext.setVisible(true);
        Bprev.setVisible(true);
        Bnext.setEnabled(true);
        Bprev.setEnabled(true);
        infolabel.setText("Laboratorio: "+lab+", giorno "+dt);
        
    }//GEN-LAST:event_BnextActionPerformed

    private void BprevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BprevActionPerformed
        // TODO add your handling code here:
                Calendar calendar = Calendar.getInstance();
        calendar.setTime(dt);
        calendar.add(Calendar.DATE, -1);
        dt = calendar.getTime();
        TableModelOccupazione mytab = new TableModelOccupazione(lab,dt,db,this);
        Table.setModel(mytab);
        Bnext.setVisible(true);
        Bprev.setVisible(true);
        Bnext.setEnabled(true);
        Bprev.setEnabled(true);
        infolabel.setText("Laboratorio: "+lab+", giorno "+dt);
    }//GEN-LAST:event_BprevActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        PrenotaDialog pr = new PrenotaDialog(this, true, db);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        PermessiDialog perm = new PermessiDialog(this, true,db);
        TableModelPermesso tbm = new TableModelPermesso(this, db, perm.getCod());
        Table.setModel(tbm);
        
        
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        StatisticheDialog stat = new StatisticheDialog(this, true, db);
        try {
             VisualizzaDialog vis;
            vis = new VisualizzaDialog(this, true, db, stat.getCod(), stat.getDatai(), stat.getDataf());
        } catch (Exception e) {
        }
       
        
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        CreaGruppoDialog gr = new CreaGruppoDialog(this, true, db);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
           try {
            // TODO add your handling code here:
            db.close();
        } catch (Exception ex) {
           
           System.exit(-2);
        }
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

 
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bnext;
    private javax.swing.JButton Bprev;
    private javax.swing.JTable Table;
    private javax.swing.JLabel infolabel;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
