/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package esame;

import java.awt.Frame;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Marco
 */
public class PermessiDialog extends javax.swing.JDialog {
        private ResultSet rs;
        private final Database db;
        private final Frame parent;
        private String q;
        private String cod;

    public String getCod() {
        return cod;
    }

    /**
     * Creates new form PermessiDialog
     * @param parent
     * @param modal
     * @param db
     */
    public PermessiDialog(Frame parent, boolean modal, Database db) {
        super(parent, modal);
        initComponents();
        this.db=db;
        this.parent = parent;
        q="SELECT DISTINCT cod FROM riservato";
       
        try {
            rs=db.queryOUT(q);
            while(rs.next()){
                Combo_locale.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            ErroreDialog err = new ErroreDialog(parent, true, ex.toString());
            this.dispose();
        }
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Combo_locale = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        button_ok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Combo_locale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_localeActionPerformed(evt);
            }
        });

        jLabel1.setText("Locale:");

        button_ok.setText("OK");
        button_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_okActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1)
                .addGap(77, 77, 77)
                .addComponent(Combo_locale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_ok)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Combo_locale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(button_ok)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_okActionPerformed
        // TODO add your handling code here:
        cod= Combo_locale.getSelectedItem().toString();
        this. dispose();
    }//GEN-LAST:event_button_okActionPerformed

    private void Combo_localeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_localeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Combo_localeActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Combo_locale;
    private javax.swing.JButton button_ok;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
