/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package esame;

import java.awt.Frame;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;

/**
 *
 * @author Marco
 */
public class VisualizzaDialog extends javax.swing.JDialog {
    private String q;
    private ResultSet rs;
    private String datai, dataf;
    /**
     * Creates new form VisualizzaDialog
     */
    public VisualizzaDialog(Frame parent, boolean modal, Database db, String cod, Date datai, Date dataf) {
        super(parent, modal);
        try {
            initComponents();
            this.datai=""+datai.getDate()+"/"+(1+datai.getMonth())+"/"+(1900+datai.getYear());
            
            this.dataf=""+dataf.getDate()+"/"+(1+dataf.getMonth())+"/"+(1900+dataf.getYear());
            codlabel.setText("Laboratorio: "+cod);
            q="SELECT COUNT(*) FROM prenotazione WHERE cod='"+cod+"' and data>='"+this.datai+"' and data<='"+this.dataf+"'";
            
            rs=db.queryOUT(q);
            rs.next();
            jLabel4.setText(rs.getString(1));
            String mesei,mesef;
           
            mesei=""+(datai.getMonth()+1);
             
             mesef=""+(dataf.getMonth()+1);
             
            q="SELECT COUNT(*) FROM assegnati WHERE cod='"+cod+"' and mese>="+mesei+" and mese<="+mesef+"";
            rs=db.queryOUT(q);
            rs.next();
            jLabel5.setText(rs.getString(1));
            
            
        } catch (SQLException ex) {
            ErroreDialog err= new ErroreDialog(parent, true, ex.toString());
        }
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        codlabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        codlabel.setText("jLabel1");

        jLabel2.setText("Prenotazioni:");

        jLabel3.setText("Assegnati");

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(codlabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(codlabel)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addContainerGap(163, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel codlabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
